spring.application.name=DigitalLibraryManagementSystem 
server.port=8081

# Changed database name to lowercase and appended recommended connection parameters
spring.datasource.url=jdbc:mysql://localhost:3306/digitallibrarymanagementsystem
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Automatically structures tables based on your JPA Entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=my-super-secret-key-for-digital-library-management-system-12345
jwt.expiration=3600000